name: Gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-develop:
    runs-on: ubuntu-latest
    concurrency:
      group: build-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      ACRA_EMAIL: ${{ secrets.ACRA_EMAIL }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Spotless
      run: ./gradlew spotlessCheck
    - name: Extract service-user.json
      run: 'echo "$SERVICE_USER" | base64 --decode > domain/src/jvmTest/resources/service-user.json'
      shell: bash
      env:
        SERVICE_USER: ${{secrets.SERVICE_USER}}
    - name: Extract google-services.json
      run: 'echo "$GOOGLE_SERVICES" | base64 --decode > app-android/google-services.json'
      shell: bash
      env:
        GOOGLE_SERVICES: ${{secrets.GOOGLE_SERVICES}}
    - name: Unit tests
      run: ./gradlew test
    - name: Upload Reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Unit Test Reports
        path: ${{ github.workspace }}/**/build/reports/**/*
        retention-days: 5
